set_property SRC_FILE_INFO {cfile:{c:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/blk_mem_gen_0_ex/imports/blk_mem_gen_0_exdes.xdc} rfile:../../../imports/blk_mem_gen_0_exdes.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab20/bh_llb.xdc} rfile:../../../../lab20/bh_llb.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 20.000 -name TS_S_CLKA [get_ports CLK_IN]
set_property src_info {type:XDC file:2 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_IN]
set_property src_info {type:XDC file:2 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {STATUS[6]}]
set_property src_info {type:XDC file:2 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {STATUS[5]}]
set_property src_info {type:XDC file:2 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {STATUS[4]}]
set_property src_info {type:XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {STATUS[3]}]
set_property src_info {type:XDC file:2 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {STATUS[2]}]
set_property src_info {type:XDC file:2 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {STATUS[1]}]
set_property src_info {type:XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {STATUS[0]}]
