# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab19/BH_DEMO.xdc

# Block Designs: bd/BH_DEMO/BH_DEMO.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BH_DEMO || ORIG_REF_NAME==BH_DEMO} -quiet] -quiet

# IP: bd/BH_DEMO/ip/BH_DEMO_jtag_axi_0_0/BH_DEMO_jtag_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BH_DEMO_jtag_axi_0_0 || ORIG_REF_NAME==BH_DEMO_jtag_axi_0_0} -quiet] -quiet

# IP: bd/BH_DEMO/ip/BH_DEMO_axi_bram_ctrl_0_0/BH_DEMO_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BH_DEMO_axi_bram_ctrl_0_0 || ORIG_REF_NAME==BH_DEMO_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/BH_DEMO/ip/BH_DEMO_axi_bram_ctrl_0_bram_0/BH_DEMO_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BH_DEMO_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==BH_DEMO_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/BH_DEMO/ip/BH_DEMO_axi_smc_0/BH_DEMO_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BH_DEMO_axi_smc_0 || ORIG_REF_NAME==BH_DEMO_axi_smc_0} -quiet] -quiet

# IP: bd/BH_DEMO/ip/BH_DEMO_clk_wiz_0/BH_DEMO_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BH_DEMO_clk_wiz_0 || ORIG_REF_NAME==BH_DEMO_clk_wiz_0} -quiet] -quiet

# IP: bd/BH_DEMO/ip/BH_DEMO_rst_clk_wiz_100M_0/BH_DEMO_rst_clk_wiz_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BH_DEMO_rst_clk_wiz_100M_0 || ORIG_REF_NAME==BH_DEMO_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/BH_DEMO/ip/BH_DEMO_system_ila_0_0/BH_DEMO_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BH_DEMO_system_ila_0_0 || ORIG_REF_NAME==BH_DEMO_system_ila_0_0} -quiet] -quiet

# XDC: bd/BH_DEMO/BH_DEMO_ooc.xdc
