@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu Feb 06 14:25:13 +0200 2025
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto ec549bb9653b45fbb02b69e4d8432f35 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip -L xpm --snapshot MMCM_4_CHANNELS_TB_behav xil_defaultlib.MMCM_4_CHANNELS_TB -log elaborate.log"
call xelab  -wto ec549bb9653b45fbb02b69e4d8432f35 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip -L xpm --snapshot MMCM_4_CHANNELS_TB_behav xil_defaultlib.MMCM_4_CHANNELS_TB -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
