# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20_b/fwdaxi/bh_llb.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_jtag_axi_0_0/design_1_jtag_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_jtag_axi_0_0 || ORIG_REF_NAME==design_1_jtag_axi_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_0 || ORIG_REF_NAME==design_1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_jtag_axi_0_axi_periph_0/design_1_jtag_axi_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_jtag_axi_0_axi_periph_0 || ORIG_REF_NAME==design_1_jtag_axi_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0 || ORIG_REF_NAME==design_1_clk_wiz_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_100M_0/design_1_rst_clk_wiz_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_100M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reset_inv_0_0/design_1_reset_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_reset_inv_0_0 || ORIG_REF_NAME==design_1_reset_inv_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
