set_property IOSTANDARD LVCMOS33 [get_ports reset_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN L16 [get_ports reset]
set_property PACKAGE_PIN J15 [get_ports reset_0]