webtalk_init -webtalk_dir C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab15/lab15.sim/sim_1/behav/xsim/xsim.dir/CALCULATOR_UNIT_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Feb 26 18:29:52 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5009c377-8929-4214-99f1-91b5f5c0fbb0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "968c826e9ac84ef79083ee263da89f83" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "67" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 7735HS with Radeon Graphics        " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3194 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "31.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "23" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "507 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "22 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "292" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "37" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.77_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "172356_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1040618903 -regid "" -xml C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab15/lab15.sim/sim_1/behav/xsim/xsim.dir/CALCULATOR_UNIT_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab15/lab15.sim/sim_1/behav/xsim/xsim.dir/CALCULATOR_UNIT_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab15/lab15.sim/sim_1/behav/xsim/xsim.dir/CALCULATOR_UNIT_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
