# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/xbip_dsp48_macro_0/xbip_dsp48_macro_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xbip_dsp48_macro_0 || ORIG_REF_NAME==xbip_dsp48_macro_0} -quiet] -quiet
