# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.cache/wt} [current_project]
set_property parent.project_path {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.board} [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_repo_paths {{c:/Users/idowe/FPGA Projects/repo}} [current_project]
update_ip_catalog
set_property ip_output_repo {c:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/other/Nexys4_all.coe}}
read_vhdl -library xil_defaultlib {
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/ADXL362Ctrl.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/AccelArithmetics.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/AccelDisplay.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/AccelerometerCtl.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/AudioDemo.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/Dbncr.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/FPGAMonitor.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/LedBar.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/LocalRst.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/LogoDisplay.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/SyncAsync.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/MicDisplay.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/MouseCtl.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/MouseDisplay.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/OverlayCtl.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/PdmDes.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/PdmSer.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/Ps2Interface.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/Pwm.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/Ram2Ddr.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/RamCntrl.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/RgbLed.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/RgbLedDisplay.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/SPI_If.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/TWICtl.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/TempDisplay.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/TempSensorCtl.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/Vga.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/sSegDemo.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/sSegDisplay.vhd}
  {C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/imports/src/hdl/top.vhd}
}
read_ip -quiet {{C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/ip/BRAM_1/BRAM_1.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/ip/BRAM_1/BRAM_1_ooc.xdc}}]

read_ip -quiet {{C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/ip/Square_Root/Square_Root.xci}}

read_ip -quiet {{C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/ip/ddr/ddr.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/ip/ddr/ddr/user_design/constraints/ddr.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/ip/ddr/ddr/user_design/constraints/ddr_ooc.xdc}}]

read_ip -quiet {{C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/ip/ClkGen/ClkGen.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/ip/ClkGen/ClkGen_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/ip/ClkGen/ClkGen.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/sources_1/ip/ClkGen/ClkGen_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/constrs_1/imports/constraints/Nexys-A7-100T-Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab23/vivado_proj/Nexys-A7-100T-OOB.srcs/constrs_1/imports/constraints/Nexys-A7-100T-Master.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Nexys4DdrUserDemo -part xc7a100tcsg324-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Nexys4DdrUserDemo.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Nexys4DdrUserDemo_utilization_synth.rpt -pb Nexys4DdrUserDemo_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
