# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab7/lab7.srcs/sources_1/ip/dual_port_ram/dual_port_ram.xci
# IP: The module: 'dual_port_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab7/lab7.srcs/sources_1/ip/dual_port_ram/dual_port_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dual_port_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab7/lab7.srcs/sources_1/ip/dual_port_ram/dual_port_ram.xci
# IP: The module: 'dual_port_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/idowe/FPGA Projects/FPGA-Course-Logtel/logtel_book_labs/lab7/lab7.srcs/sources_1/ip/dual_port_ram/dual_port_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dual_port_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
