set_property SRC_FILE_INFO {cfile:C:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/blk_mem_gen_0_ex/imports/blk_mem_gen_0_exdes.xdc rfile:../../../imports/blk_mem_gen_0_exdes.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/blk_mem_gen_0_ex/fwdaxi/bh_llb.xdc rfile:../../../fwdaxi/bh_llb.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 20.000 -name TS_S_CLKA [get_ports CLK_IN]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports interrupt]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D4 [get_ports tx]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C4 [get_ports rx]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk_in1]
set_property src_info {type:XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M13 [get_ports aresetn]
set_property src_info {type:XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports reset_1]
set_property src_info {type:XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports reset_1]
