@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Feb 16 17:39:14 +0200 2025
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim MULTIPLIER_UNIT_TB_behav -key {Behavioral:sim_1:Functional:MULTIPLIER_UNIT_TB} -tclbatch MULTIPLIER_UNIT_TB.tcl -log simulate.log"
call xsim  MULTIPLIER_UNIT_TB_behav -key {Behavioral:sim_1:Functional:MULTIPLIER_UNIT_TB} -tclbatch MULTIPLIER_UNIT_TB.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
