#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Sep 14 14:57:42 IST 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto c090f5f7cbba442db8cc4030d7221e00 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L utilities_lib -L specific_support_lib -L secureip --snapshot test_uart_rx_behav xil_defaultlib.test_uart_rx -log elaborate.log"
xelab -wto c090f5f7cbba442db8cc4030d7221e00 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L utilities_lib -L specific_support_lib -L secureip --snapshot test_uart_rx_behav xil_defaultlib.test_uart_rx -log elaborate.log

