# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/dual_port_ram/dual_port_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dual_port_ram || ORIG_REF_NAME==dual_port_ram} -quiet] -quiet
