# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.cache/wt [current_project]
set_property parent.project_path C:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.3 [current_project]
set_property ip_output_repo c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files C:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_jtag_axi_0_0/constraints/jtag_axi.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_jtag_axi_0_0/constraints/design_1_jtag_axi_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_jtag_axi_0_0/constraints/design_1_jtag_axi_0_0_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_jtag_axi_0_0/design_1_jtag_axi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/bd_48ac_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all C:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/level_C/level_C.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/bh_ddr_demo_wrapper.xdc
set_property used_in_implementation false [get_files C:/Users/idowe/myProjects/FPGA-Course-Logtel/logtel_book_labs/lab20/level_C/bh_ddr_demo_wrapper.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
